### ISSUE TITLE
Mod makes my forge crash

### ISSUE THREAD

**Issue by TermitCG** [isXander/EvergreenHUD#8]
Logs:
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (AutoGG-4.0.3 (1.8.9).jar)
  Powns' Ghost Lava Fix ([1.8.9] Powns Ghost Liquid Fix.jar)
  McLib core mod (mclib-2.1.1-1.8.9.jar)
  FMLLoadingPlugin (Levelhead-7.2 (1.8.9).jar)
  Perspective Mod ([1.8.9] Perspective Mod-3.0.jar)
  FMLLoadingPlugin (Motion Blur-2.0 (1.8.9).jar)
  PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  BlurPlugin (Blur-MC1.8.9-1.0.4-2.jar)
  HytilitiesTweaker (Hytilities-1.0_-_beta_6.jar)
  FMLLoadingPlugin (EvergreenHUD.1.8.9-2.0-RC.3.jar)
  ItemPatchingLoader (itemphysic_lite_1.3_mc1.8.9.jar)
  RenderPlayerAPIPlugin (RenderPlayerAPI-1.8.9-1.0.jar)
  BossbarTweaker (Bossbar Customizer-1.2 (1.8.9).jar)
  PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  FMLLoadingPlugin (Keystrokes-8.0.2 (1.8.9).jar)
  ModTweaker (Patcher-1.5.1 (1.8.9).jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 30.06.21 22:49
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at co.uk.isxander.xanderlib.utils.HttpsUtils.getString(HttpsUtils.java:56)
	at co.uk.isxander.evergreenhud.repo.BlacklistManager.isVersionBlacklisted(BlacklistManager.java:27)
	at co.uk.isxander.evergreenhud.EvergreenHUD.init(EvergreenHUD.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at co.uk.isxander.xanderlib.utils.HttpsUtils.getString(HttpsUtils.java:56)
	at co.uk.isxander.evergreenhud.repo.BlacklistManager.isVersionBlacklisted(BlacklistManager.java:27)
	at co.uk.isxander.evergreenhud.EvergreenHUD.init(EvergreenHUD.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 267957936 bytes (255 MB) / 1054867456 bytes (1006 MB) up to 1900019712 bytes (1812 MB)
	JVM Flags: 1 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 41 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHI	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHI	perspectivemod{3.0} [Perspective Mod 3.0] (minecraft.jar) 
	UCHI	lavafix{1.0} [Powns' Ghost Lava Fix] (minecraft.jar) 
	UCHI	itemphysic{1.3.0} [ItemPhysic] (minecraft.jar) 
	UCHI	PlayerAPI{1.0} [Player API] (minecraft.jar) 
	UCHI	RenderPlayerAPI{1.0} [Render Player API] (minecraft.jar) 
	UCHI	level_head{7.2} [Sk1er Level Head] (minecraft.jar) 
	UCHI	customdiscordrpc{2.21-[1.8,1.8.9]} [Custom Discord RPC] (customdiscordrpc-2.21-[1.8,1.8.9].jar) 
	UCHI	autotip{3.0.1} [Autotip] (Autotip-3.0.1 [1.8-1.12.2].jar) 
	UCHI	replaymod{1.8.9-2.5.2} [Replay Mod] (replaymod-1.8.9-2.5.2.jar) 
	UCHI	modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
	UCHI	xanderlib{0.8} [XanderLib] (xanderlib.jar) 
	UCHI	blockoverlay{2.1} [BlockOverlay] ([1.8.9] BlockOverlay-v2.1.jar) 
	UCHI	customcrosshairmod{0.5.1-Forge} [Custom Crosshair Mod] ([1.8.9] Crosshairmod-v0.5.1.jar) 
	UCHI	wingsmod{1.2} [Wings Mod] ([1.8.9]+Wings+Mod-1.2.jar) 
	UCHI	bspkrscore{1.8.9.2} [bspkrsCore] ([1.8.9]bspkrsCore-universal-1.8.9.2.jar) 
	UCHI	autogg{4.0.3} [AutoGG] (AutoGG-4.0.3 (1.8.9).jar) 
	UCHI	betterchat{1.5} [Better Chat] (betterchat-1.5.jar) 
	UCHI	blur{MC1.8.9-1.0.4-2} [Blur] (Blur-MC1.8.9-1.0.4-2.jar) 
	UCHI	bossbar_customizer{1.2} [BossbarCustomizer] (Bossbar Customizer-1.2 (1.8.9).jar) 
	UCHI	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
	UCHI	mclib{2.1.1} [McLib] (mclib-2.1.1-1.8.9.jar) 
	UCHI	emoticons{0.6.1} [Emoticons] (emoticons-0.6.1-1.8.9-dist.jar) 
	UCHE	evergreenhud{2.0-RC.3} [EvergreenHUD] (EvergreenHUD.1.8.9-2.0-RC.3.jar) 
	UCHI	hypixel_auto_complete{1.0} [Hypixel Autocomplete Mod] (Hypixel Autocomplete-1.0 (1.8.9).jar) 
	UCHI	hytilities{0.1} [Hytilities] (Hytilities-1.0_-_beta_6.jar) 
	UCHI	keystrokesmod{8.0.2} [KeystrokesMod] (Keystrokes-8.0.2 (1.8.9).jar) 
	UCHI	motionblurmod{2.0} [Motion Blur] (Motion Blur-2.0 (1.8.9).jar) 
	UCHI	MumbleLink{1.8.9-4.1.4} [MumbleLink for Forge] (MumbleLink-1.8.9-4.1.4.jar) 
	UCHI	ExtendedPASupport{1.0.0} [ExtendedPASupport for MumbleLink] (MumbleLink-1.8.9-4.1.4.jar) 
	UCHI	animations{6.7} [Orange's 1.7 Animations] (Orange's+1.7+Animations-6.7.jar) 
	UCHI	patcher{1.5.1} [Patcher] (Patcher-1.5.1 (1.8.9).jar) 
	UCHI	quickplay{2.0.5} [Quickplay] (Quickplay-1.8.9-2.0.5.jar) 
	UCHI	simplecapes{1.0} [Simple Capes] (SimpleCapes-1.0-SNAPSHOT.jar) 
	UCHI	smooth-scrolling-everywhere{1.1} [Smooth Scrolling Everywhere] (smooth-scrolling-everywhere-1.1.jar) 
	UCHI	timechanger{2.1} [TimeChanger] (TimeChanger-2.2.1.jar) 
	UCHI	ToggleSneak{3.2.2} [ToggleSneak] (ToggleSneak-(1.8.9)-v3.2.2.jar) 
	UCHI	sk1er_fullscreen{1.0} [Sk1er Fullscreen] (Windowed Fullscreen-1.0 (1.8.9).jar) 
	UD	mclib_core{2.1.1} [McLib core mod] (minecraft.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (AutoGG-4.0.3 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
Powns' Ghost Lava Fix ([1.8.9] Powns Ghost Liquid Fix.jar)
  me.powns.lavafix.asm.PlayerControllerMPTransformer
  me.powns.lavafix.asm.ItemBucketTransformer
McLib core mod (mclib-2.1.1-1.8.9.jar)
  mchorse.mclib.core.McLibCMClassTransformer
FMLLoadingPlugin (Levelhead-7.2 (1.8.9).jar)
  club.sk1er.mods.levelhead.forge.transform.ClassTransformer
Perspective Mod ([1.8.9] Perspective Mod-3.0.jar)
  net.canelex.perspectivemod.asm.CameraTransformer
FMLLoadingPlugin (Motion Blur-2.0 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.patcher.tweaker.ClassTransformer
BlurPlugin (Blur-MC1.8.9-1.0.4-2.jar)
  com.tterrag.blur.BlurTransformer
HytilitiesTweaker (Hytilities-1.0_-_beta_6.jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.hytilities.tweaker.ClassTransformer
FMLLoadingPlugin (EvergreenHUD.1.8.9-2.0-RC.3.jar)
  
ItemPatchingLoader (itemphysic_lite_1.3_mc1.8.9.jar)
  com.creativemd.itemphysic.ItemTransformer
RenderPlayerAPIPlugin (RenderPlayerAPI-1.8.9-1.0.jar)
  api.player.forge.RenderPlayerAPITransformer
BossbarTweaker (Bossbar Customizer-1.2 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.bossbarcustomizer.tweaker.ClassTransformer
PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  api.player.forge.PlayerAPITransformer
FMLLoadingPlugin (Keystrokes-8.0.2 (1.8.9).jar)
  
ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 465.89, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !               §b Clvqn §f[16x].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 465.89
	OpenGlRenderer: NVIDIA GeForce GT 1030/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4`

**Comment by koxx12-dev** [comment]
please use hastebin for logs this hurts

**Comment by wyvest** [comment]
recommendations:
1. update perspective mod to dj's perspective mod (https://github.com/DJtheRedstoner/PerspectiveModv4/releases/tag/v4.3)
2. Remove PlayerAPI and RenderPlayerAPI
3. Replace Custom Discord RPC with HyCord (if you play Hypixel mainly) (https://github.com/DeDiamondPro/HyCord/releases/tag/1.1.2)
4. Update Block Overlay (https://hypixel.net/threads/forge-1-8-9-block-overlay-v4-0-3.1417995/)
5. Update Custom Crosshair mod
6. Replace Old Animations Mod with Sk1er's Old Animations (sk1er.club/beta)
7. Replace ToggleSneak with SimpleToggleSneak (https://github.com/My-Name-Is-Jeff/SimpleToggleSprint/releases/download/v1.2.1/SimpleToggleSprint-1.2.1.jar)

**Comment by isXander** [comment]
My best guess is you had an Internet issue. I will and make this a non-fatal error in the next update.
